name: Czech Communication Group
favicon: null
layout_spectrum: 0.74895
typography_spectrum: 0.2637
title: 'Krizová komunikace, PR, eventy, mediální vztahy, sociální sítě, marketing. CCG.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1fb8f1'
    - '#f01e9b'
    - '#231f20'
    - '#817e7f'
  brandStrength: 0.1875
  lightness: 0.1875
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
