layout_spectrum: 0.8873631784226745
typography_spectrum: 0.2318058938253671
color:
  brandColors:
    - '#ffffff'
    - '#1fb8f1'
    - '#f01e9b'
    - '#231f20'
    - '#817e7f'
  brandStrength: 0.375
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.25
name: Czech Communication Group
favicon: null
title: 'Krizová komunikace, PR, eventy, mediální vztahy, sociální sítě, marketing. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77010025-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
