name: Czech Communication Group
favicon: null
layout_spectrum: 0.52258
typography_spectrum: 0.61837
title: 'Krizová komunikace, PR, eventy, mediální vztahy, sociální sítě, marketing. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1fb8f1'
    - '#f01e9b'
    - '#231f20'
    - '#817e7f'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
